fancy indexing

In [2]:
import numpy as np

rng = np.random.default_rng()

x = rng.integers(0,10,(6,5))
print(x)

[[2 9 6 2 5]
 [2 2 2 8 6]
 [3 2 7 6 3]
 [2 1 3 7 7]
 [0 9 3 3 6]
 [8 3 6 4 2]]


In [24]:
# manual indexing
print(x[0][3], x[2][3], x[1][4])

# fancy indexing
x_ind = [0, 2, 1]
y_ind = [3, 3, 4]
print(x[x_ind, y_ind])

# combined indexing
print(x[2, [0, 3, 4]])

# fancy indexing and slicing
print(x[2:, [3,2,1]])


2 6 6
[2 6 6]
[3 6 3]
[[6 7 2]
 [7 3 1]
 [3 3 9]
 [4 6 3]]


In [ ]:
# modifying values with fancy indexing