Reviewing python lists, contiguous arrays, and NumPy arrays

In [2]:
import numpy as np

In [3]:
# create list of zeroes
print(np.zeros(10, dtype = int))

# create 2d list of zeroes
print(np.zeros((4,4)))

# create incremeting list
print(np.arange(0,20))

# create array of values equally spaced in a range
print(np.linspace(0,5,5))

[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0.   1.25 2.5  3.75 5.  ]


In [4]:
x1 = np.ones((8,8))
print(x1)
x1_sub = x1[3:6, 4:7]
x1_sub[0,0] = 30
x1_sub[0,1] = 45
x1_sub[1,0] = 32
x1_sub[1,1] = 12
print(x1)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1. 30. 45.  1.  1.]
 [ 1.  1.  1.  1. 32. 12.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]


In [10]:
# reshape array

x = np.zeros(10)
print(x)
print(x.reshape((2,5)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
