3 rules of broadcasting

1. If the two arrays differ in num dimensions, the shape of the one with fewer dimensions is padded with ones on it's left side
2. If the shape of the two arrays does not match in any dimension, the array with shape 1 in that dimension is stretched to match the other shape
3. If the sizes disagree in any dimension, and neither is equal to 1, error is raised

In [1]:
import numpy as np

In [ ]:
m = np.ones((3,3))
print(m)

a = np.array([1,2,3])
print(a)

m + a # broadcasted (1,2,3) onto all dimensions of the 2d array

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [ ]:
b = np.arange(3)
print(b)
c = np.arange(3)[:,np.newaxis]
print(c)

b + c # broadcasts in 2 dimensions given 2 1-d arrays

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])